[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "EoXDvKpyju8yYcV5MP7BAULnffvKoRfXGxVriDg7MCJy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
rpc_port = 8899                                 # Set JSON RPC on this port, and the next port for the RPC websocket.
gossip_port = 8001                             # Gossip port number for the validator.
gossip_host = "127.0.0.1"                       # Gossip DNS name or IP address for the validator to advertise in gossip.
faucet_port = 9900                             # Enable the faucet on this port.
dynamic_port_range = "8000 - 10000"             # Range to use for dynamically assigned ports.
bind_address = "127.0.0.1"                        # IP address to bind the validator ports.

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
